version: "3.9"
services:
  evaluator:
    image: ghcr.io/inglemoor-coding-computing/ihs-ccc-evaluator:main
    container_name: ihs-ccc-eval
    ports:
      - 1313:80
    restart: always
    environment:
      - ExecutionEndpoint="http://exec-runner:1989/execute"
      - JWT__Secret="${JWT_Secret}"
      - Admin__Password="${ADMIN_PASSWORD}"

  exec-runner:
    image: ghcr.io/inglemoor-coding-computing/ihs-ccc-evaluator-runner:main
    container_name: ihs-ccc-eval-exec-runner
    restart: always
    ports:
      - 1989:80
    environment:
      - Endpoint="http://piston:2000/api/v2/execute"

  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: always
    ports:
      - 2000:2000
    volumes:
      - ./data/piston/packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000,mode=711
      - /tmp:exec

  # watchtower:
  #   image: containrrr/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /root/.docker/config.json:/config.json
  #   command: --interval 60
  #   restart: always
