version: "3.9"
services:
  evaluator-dev:
    build: 
      context: .
      dockerfile: ./src/InglemoorCodingComputing.Evaluator/Dockerfile
    container_name: ihs-ccc-eval-dev
    ports:
      - 1313:80
    restart: always
    volumes:
      - ./data/ihs-ccc-eval:/app/ihs-ccc-eval
    environment:
      - ExecutionEndpoint="http://exec-runner:1989/execute?key=1234"
      - JWT__Secret=${JWT_Secret}
      - Admin__Password=${Admin_Password}

  exec-runner:
    build: 
      context: .
      dockerfile: ./src/InglemoorCodingComputing.Evaluator.ExecutionRunner/Dockerfile
    container_name: ihs-ccc-eval-exec-runner-dev
    restart: always
    ports:
      - 1989:80
    environment:
      - Endpoint="http://piston:2000/api/v2/execute"
      - Key=1234

  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: always
    ports:
      - 2000:2000
    volumes:
      - ./data/piston/packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000,mode=711
      - /tmp:exec
