version: "3.9"
services:
  evaluator-dev:
    image: ghcr.io/inglemoor-coding-computing/ihs-ccc-evaluator:main
    container_name: ihs-ccc-eval
    ports:
      - 1313:80
    restart: always
    volumes:
      - ./data/ihs-ccc-eval:/data
    environment:
      - ExecutionEndpoint=http://exec-runner:80,1234
      - JWT__Secret=${JWT_Secret}
      - Admin__Password=${Admin_Password}
      - XDG_DATA_HOME=/data

  exec-runner:
    image: ghcr.io/inglemoor-coding-computing/ihs-ccc-evaluator-runner:main
    container_name: ihs-ccc-eval-exec-runner
    restart: always
    ports:
      - 1989:80
    environment:
      - Endpoint=http://piston:2000
      - Key=1234

  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: always
    ports:
      - 2000:2000
    volumes:
      - ./data/piston/packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000,mode=711
      - /tmp:exec
    environment:
      - PISTON_MAX_CONCURRENT_JOBS=32
      - PISTON_MAX_PROCESS_COUNT=8
      - PISTON_MAX_FILE_SIZE=1000000

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60
    restart: always
